### ISSUE TITLE
missing info in the doc

### ISSUE THREAD

**Issue by chrplr** [neurospin/neurospin_to_bids#18]
The possible values for the 'location' field should be indicated in the doc. 

The `exp_info` example  provide `trio`, but the folder on /neurospin/acquisition are
---
Investigational_Device_7T  
Prisma_fit  
TrioTim
---
Also, it is not super clear from the README that the script is interactive. I was looking for the command line option to run pydeface, and it is only after launching neurospin_to_bids that I saw that it was asked interactively.

**Comment by isadenghien** [comment]
The doc has been updated. The non-interactive mode wasn't really for users, but more for very advanced users.
Add also information about the possible labels for location column.
