### ISSUE TITLE
Optionally create sourcedata directory

### ISSUE THREAD

**Issue by ylep** [neurospin/neurospin_to_bids#2]
Optionally create a `sourcedata` directory with symbolic links to the DICOMs on `/neurospin/acquisition`.

**Comment by DimitriPapadopoulos** [comment]
Totally agree, I had already attempted that in the past. But then don't we need to sort acquisitions by project?

**Comment by ylep** [comment]
My suggestion is to write a `sourcedata` directory next to the `rawdata` (BIDS) directory, based on the contents of `participants_to_import.tsv`. That directory will have symlinks into `/neurospin/acquisition`.

In that scheme, `participants_to_import.tsv` remains the place where the list of acquisitions in a given project is declared. I don't think it’s feasible to group acquisitions by project directly on `/neurospin/acquisition` (acquisitions may be part of multiple analysis projects, that we only devise after the fact...)

**Comment by ylep** [comment]
Implemented in https://github.com/neurospin/neurospin_to_bids/commit/657545a6e56a2c6fe552778ec1579fea075f669e
