### ISSUE TITLE
/i2bm → /drf

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [neurospin/neurospin_to_bids#33]
@ylep Comment faire prendre en compte le commit https://github.com/neurospin/neurospin_to_bids/commit/c56f31ac0fd5ecd39cd8cb0d94c76829b619b307 au plus vite ?

**Comment by ylep** [comment]
Production deployment launched manually for Ubuntu 22.04 (Python 3.10) and Ubuntu 20.04 (Python 3.8). The `master` branch should be deployed in production in a few minutes.
